### ISSUE TITLE
Looking for a maintainer?

### ISSUE THREAD

**Issue by NotAmaan** [mcchrish/feathers-objection#12]
Hey @mcchrish,

I'd be interested in maintaining this project if you're interested as we're actively using this in a project.

**Comment by mcchrish** [comment]
@NotAmaan that would be really awesome. I have no problem handing it to anyone willing to maintain as long as it follows the direction feathers is going.

Sorry for not being able to maintain this library at the moment.

**Comment by mcchrish** [comment]
@NotAmaan do you also want to be added to the npm maintainer?
