### ISSUE TITLE
Support for mergeAllowEager

### ISSUE THREAD

**Issue by chrisronline** [mcchrish/feathers-objection#14]
Hi,

I've been using this for the past couple weeks and it's been working great, but I was wondering if this library supports [mergeAllowEager](https://vincit.github.io/objection.js/#mergealloweager)? I didn't see it anywhere in the docs and I didn't see anything in the source code, but just wanted to check.

Thanks

**Comment by mcchrish** [comment]
@chrisronline sorry for a very late response. Currently it's not supported. It does looks nice as an API where we allow arrays in eager queries instead of just a string.

I don't have much time to look into it, but contributions are always welcome 👍

**Comment by dekelev** [comment]
@chrisronline v1.2.0 added support for `mergeAllowEager`.

Pass `params.mergeAllowEager` to dynamically merge the given expression with the service's `allowEager` expression for each service call.

It allows to maintain a base `allowEager` list for a service and to extend it in the service hooks using some logic, like the user permission role.
