### ISSUE TITLE
Problem with createdAt and updateAt timestamps when updating

### ISSUE THREAD

**Issue by donniefargo** [mcchrish/feathers-objection#20]
Hi

I'm not able to implement timestamps properly when extending your service class.
After updating an entity the createdAt field is null. Looks like this can only be changed from
within the service itself or completely overwriting your update method.

```
const { Service } = require('feathers-objection');
const uuid = require('uuidv4');

module.exports = class BaseService extends Service {
  create(data, params) {
    if(!Array.isArray(data)) data = [data];

    for(let i = 0; i < data.length; i++) {
      data[i].id = uuid();
      data[i].createdAt = new Date().toISOString();
      delete data[i].updatedAt;
    }
    if(data.length === 1) data = data[0];
    return super.create(data, params);
  }

  update(id, data, params) {
    data.updatedAt = new Date().toISOString();
    delete data.createdAt;
    return super.update(id, data, params);
  }

  patch(id, data, params) {
    data.updatedAt = new Date().toISOString();
    delete data.createdAt;
    return super.patch(id, data, params);
  }
}
```

**Comment by donniefargo** [comment]
``update(id, data, params) {

    data.updatedAt = new Date().toISOString();
    delete data.createdAt;

    if (Array.isArray(data)) {
      return Promise.reject(new Error('Not replacing multiple records. Did you mean `patch`?'));
    }

    // NOTE (EK): First fetch the old record so
    // that we can fill any existing keys that the
    // client isn't updating with null;
    return this._get(id, params).then(oldData => {
      let newObject = { ...oldData, ...data };

      // NOTE (EK): Delete id field so we don't update it
      delete newObject[this.id];

      return this._createQuery(params).where(this.id, id).update(newObject).then(() => {
        // NOTE (EK): Restore the id field so we can return it to the client
        newObject[this.id] = id;
        return { id, ...newObject};
      });
    }).catch(function(err) { throw Error(err) });
  }``

**Comment by dekelev** [comment]
Please try this example in your Model to automatically set the `createdAt` & `updatedAt` fields:

```
const { Model } = require('objection');

class User extends Model {

  static get tableName() {
    return 'user';
  }

  static get jsonSchema() {
    return {
      type: 'object',
      required: ['name'],

      properties: {
        id: { type: 'integer' },
        name: { type: 'string' }
      }
    };
  }

  $beforeInsert() {
    this.createdAt = new Date().toISOString();
    this.updatedAt = new Date().toISOString();
  }

  $beforeUpdate() {
    this.updatedAt = new Date().toISOString();
  }
}

module.exports = User;
```
