### ISSUE TITLE
Error when searching by eager value

### ISSUE THREAD

**Issue by Aerlin** [mcchrish/feathers-objection#26]
In my test project, I have two models. User (id, username, password) and Message (id, userId, text).
```
class Message extends Model {
	static get tableName() {
		return 'messages';
	}
	static get relationMappings() {
		var User = require("./users");
		return {
			user: {
				relation: Model.BelongsToOneRelation,
				modelClass: User,
				join: {
					from: 'messages.userId',
					to: 'users.id'
				}
			}
		};
	}
}
...
app.use('/messages', ObjectionService({
	model: Message,
	id: 'id',
	paginate: {
		default: 10,
		max: 100
	},
	allowedEager: '[user]'
}))
```

If I query messages by userId `/messages?userId=1` it works.   
If I query messages by user.username `/messages?$joinEager=user&user.username=Bob` I get an error.

> error: select count("id") as "total" from "messages" where "user"."username" = $1 - missing FROM-clause entry for table "user"
  
  
Now if I comment out `this.objectify(countQuery, query)` within the _find() function, the server responds properly including the total value.
`
{
  "total": 11,
  "limit": 10,
  "skip": 0,
  "data": [
    ...
  ]
}
`  

But I'm not sure if I'm breaking anything by removing that line. Am I'm doing something wrong?

**Comment by dekelev** [comment]
Please upgrade `feathers-objection` to the latest version and try the new `$joinRelation`parameter to filter based on a relation's field. check the [docs](https://github.com/mcchrish/feathers-objection) for an example of it can be used.

**Comment by Aerlin** [comment]
Thanks dekelev. v1.0.5 seems to have fixed the issue.
