### ISSUE TITLE
Support for filtering by json column attribute

### ISSUE THREAD

**Issue by Aerlin** [mcchrish/feathers-objection#33]
I have a jsonb column in my table. So far I haven't figured out how to filter by an attribute within the column. 

Glancing at Objection's [jsonQueries.js](https://github.com/Vincit/objection.js/blob/master/tests/integration/jsonQueries.js#L1414) file, it looks like wrapping the column name in a ref() call will let you query the value. 

If that's the case. Would it be possible to add an additional service option for column names to wrap ref around?

**Comment by dekelev** [comment]
@Aerlin v1.2.1 added support for querying on [JSON column](https://github.com/mcchrish/feathers-objection#json-column)

**Comment by Aerlin** [comment]
Thank you @dekelev !
