### ISSUE TITLE
Unneeded filterQuery redefinition

### ISSUE THREAD

**Issue by vonagam** [mcchrish/feathers-objection#39]
Currently you can safely remove [`filterQuery`](https://github.com/mcchrish/feathers-objection/blob/95c7cfeac8791e063eb1207113e7c12422e2d554/src/index.js#L108) and nothing will change.

First, it should exit [`here`](https://github.com/mcchrish/feathers-objection/blob/95c7cfeac8791e063eb1207113e7c12422e2d554/src/index.js#L116) because `filtered.query` will be an object. I assume it is a typo and it should have been `if (! utils.isPlainObject(query))`, it would make sense that way. 

But even after this, `convertOperators` is converting operators, but `const key = operators[prop] ? operators[prop] : prop` will always be `prop` itself. [`defaultOperators`](https://github.com/mcchrish/feathers-objection/blob/95c7cfeac8791e063eb1207113e7c12422e2d554/src/index.js#L43) returns object where keys and values are equal, there is no mismatch or converting.

Am i missing something?

**Comment by dekelev** [comment]
@vonagam thanks for this. I've took the updated version of `filterQuery` method from [feathers-sequelize](https://github.com/feathersjs-ecosystem/feathers-sequelize/blob/master/lib/index.js#L58) and it looks like it was already fixed there. The fix is published in feathers-objection v2.0.1

**Comment by vonagam** [comment]
Hm... so you keep this method for convenience, to be comparable with `feathers-sequelize` in migration paths?

Because there is no need for `convertOperators  in `feathers-objection` right now otherwise.

**Comment by vonagam** [comment]
Ok. Got it.

(Just to be clear: Ran tests. Removed `filterQuery` method, saw two failings. Fixed by reassignment of whitelist in options `super(Object.assign({...}, options, {whitelist}))` [here](https://github.com/mcchrish/feathers-objection/blob/c2f367fdf46a45ddd6c04ff496141328f92c51a1/src/index.js#L81). All tests are passing.)

**Comment by dekelev** [comment]
`$like` is in the whitelist operators list. it should not be added to the service options.

**Comment by vonagam** [comment]
Why not?  [`options.whitelist`](https://github.com/feathersjs/feathers/blob/96ad17714c0f01adfe8816bb78a217f8a0e9cc03/packages/adapter-commons/lib/service.js#L42) is for `additionalOperators` in [`filterQuery`](https://github.com/feathersjs/feathers/blob/96ad17714c0f01adfe8816bb78a217f8a0e9cc03/packages/adapter-commons/lib/filter-query.js#L107). And it is its only usage. And `$like` is additional operator used in `feathers-objection`.

**Comment by dekelev** [comment]
$like is not unique to feathers-objection and is part of the operators that are allowed now by default in feathers-sequelize. It shouldn't be different in feathers-objection.

**Comment by vonagam** [comment]
In [`feathers-objection`](https://github.com/mcchrish/feathers-objection/blob/c2f367fdf46a45ddd6c04ff496141328f92c51a1/src/index.js#L109):
`const filtered = super.filterQuery(params, { operators: this.whitelist })`

In [`feathers-sequelize`](https://github.com/feathersjs-ecosystem/feathers-sequelize/blob/3a6d44e0642d073997ade8eec797f1f3e1b0c943/lib/index.js#L59):
`const filtered = super.filterQuery(params);`

So currently they have different in behaviour.

In `feathers-objection` all operators are allowed, and you can enable additional (like `$eager`, which is really a filter), but you can't disable `$like` operator for example.

In `feathers-sequelize` all operators are allowed by default, but if you pass `whitelist` option and it does not include `$like` then `$like` will not be allowed.

**Comment by vonagam** [comment]
Ok, you can simply remove `filterQuery` and fix test to match feathers-sequelize's behaviour by adding `$like` to this [`whitelist`](https://github.com/mcchrish/feathers-objection/blob/c2f367fdf46a45ddd6c04ff496141328f92c51a1/test/index.test.js#L161).

Otherwise [this](https://github.com/mcchrish/feathers-objection/blob/c2f367fdf46a45ddd6c04ff496141328f92c51a1/test/index.test.js#L810) test will fall, because `$like` is used but not whitelisted.

**Comment by vonagam** [comment]
My mistake, you can't disable `$like` in `feathers-sequelize`. They currently do have same behaviour.

**Comment by dekelev** [comment]
OK, thanks for that check.

**Comment by vonagam** [comment]
Sorry, no mistake, you can disable `$like` in feathers-sequelize and can't in feathers-objection.

**Comment by dekelev** [comment]
:) ok, releasing a patch

**Comment by dekelev** [comment]
removing filterQuery method

**Comment by vonagam** [comment]
It's a breaking change, though, if you want to match sequelize behaviour.

**Comment by dekelev** [comment]
right, so minor version.

**Comment by vonagam** [comment]
I mean, that if somebody used `{ "whitelist": [ "$eager" ] }` and used `$like` in tests. (Like in current tests) And you change behaviour to sequelize's. Than their code will fail (Like tests was). And than they have to add `$like` to`whitelist` (Like what you need to fix tests if you match sequelize).

So it is major version change.

**Comment by dekelev** [comment]
OK. It'll be 3.0.0

**Comment by vonagam** [comment]
[Here](https://github.com/vonagam/feathers-objection/commit/2c9bf7a284b849c99b7c3246331eda41374f42f8) is if you remove all unneeded stuff.

**Comment by dekelev** [comment]
Cool. removed all that too.

**Comment by dekelev** [comment]
published as 3.0.0
