### ISSUE TITLE
How to filter based on related entities?

### ISSUE THREAD

**Issue by cdelaorden** [mcchrish/feathers-objection#9]
Hi, great job on this library, thanks for the effort.

I can't find my way around filtering a query using nested fields loaded through a relation mapping. Eager filtering will send the parent relation with nulls in the nested relation fields, when the idea should be to NOT include those parents in the results. 

For example, if you have Post and Comment, with Comment having a BelongsToOne relation to Post, and you want to load comments only for posts that are published, you can't do something like

`comments.find({ query: { $eager: '[post]', 'post.published': true })`

It throws saying 'post.state' is not a column of 'comment' table.

Doing something like that with standard SQL or knex is trivial because joined fields are part of the result set and thus you can use them in your `.where` filters.

This is specially important when you add pagination to the mix, because you want to retrieve N results that really match the expected query, not filtering out in the client or in a post hook.

Any idea or workaround, or is this simply not possible?

Edit: in the original Objection library you can do it with joinRelation, see here:
https://github.com/Vincit/objection.js/issues/541#issuecomment-334775713

**Comment by mcchrish** [comment]
Hi @cdelaorden, can you confirm if you have the result you desire on the latest version 0.8.0?

Feel free to close the issue if so.

**Comment by cdelaorden** [comment]
Hi @mcchrish yes I think it does, but I will test it in my app and close with a example, will let you know asap.

In fact, my pull request was missing some docs for the README, I may PR again for that. No need to re-publish on npm just for docs.

**Comment by dekelev** [comment]
Hi @mcchrish, this library is very powerfull, but `JoinEagerAlgorithm` doesn't seems to work for a simple use case of eager relation load with a `where` on the relation's columns. rows without relation matching the `where` query returns too and are included in the `total` count.

The only solution I found was to use `joinRelation`.

As a workaround, I'm currently using my service's Model in the the service's before find hook to query Objection directly:

```
hook.result = {};

const countResults = await Account
  .query()
  .joinRelation('users(active)')
  .count('* as count');

hook.result.total = countResults[0].count;

hook.result.data = await Account
  .query()
  .joinRelation('users(active)')
  .eager('users(active)');
```

Any chance to integrate `joinRelation` into the library? maybe as an addition query property?

**Comment by dekelev** [comment]
Please upgrade `feathers-objection` to the latest version and try the new `$joinRelation`parameter to filter based on a relation's field. check the [docs](https://github.com/mcchrish/feathers-objection) for an example of it can be used.
